---
deployment:
  tasks:
    - export DEPLOYPATH=/home/zulh7811/public_html/

    # Copy seluruh isi folder public ke public_html
    - /bin/cp -R public/* $DEPLOYPATH

    # Copy app, writable, vendor ke public_html
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH

    # Copy file-file root project
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH

    # Copy deploy index ke public_html
    - /bin/cp deploy_index.php $DEPLOYPATH/index.php
