deployment:
  tasks:
    - export DEPLOYPATH=/home/zulh7811/public_html/
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
