---
deployment:
  tasks:
    # Path folder public_html di hosting
    - DEPLOYPATH=/home/zulh7811/public_html/

    # Bersihkan folder lama (opsional, sangat aman)
    - /bin/rm -rf $DEPLOYPATH/*

    # Copy seluruh isi folder public ke public_html
    - /bin/cp -R public/* $DEPLOYPATH

    # Copy folder CodeIgniter penting
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R writable $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH

    # Copy file-file penting root CI4
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH

    # Copy file php custom yang berada di folder root (seperti kontol.php)
    - /bin/cp *.php $DEPLOYPATH

    # Replace index.php hosting dengan deploy_index.php
    - /bin/cp deploy_index.php $DEPLOYPATH/index.php
